version: '3'

services:
  web:
    image: mrsme/django_vue
    build: .
    command:  >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/home/docker/code